[project]
name = "airflow-orchestrator"
version = "0.1.0"
description = "Write simple Airflow to work with Airbyte"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow==2.10.3",
    "apache-airflow-providers-airbyte==5.2.0",
]
